Correcciones del código
Joanna20Carrion/TP1_Mejorado pull request #4
Opened 2024-07-16 04:06 UTC by Joanna20Carrion

2024-07-16 22:40 UTC, scaprile requested changes
Es preferible, como dijimos, que sigas trabajando sobre el mismo PR original. Todos los commits se pueden ver por separado si es necesario chequear los cambios. Así nos sacás del contexto original.

2024-07-16 22:40 UTC, scaprile commented on main.cpp
> +        }
Incorrectamente incorrecto de toda incorrectitud incorrecta.
Eso sólo sería así en un sistema multitarea, que no lo es, y de todos modos esta tarea bloquearía. Tenés que aprender a escribir código en serio

2024-07-21 22:28 UTC, EFilomena commented on main.cpp
> +        }
Podés pensar algo así:

void xxxxxxxxxxx() {
        cont++;
	if (cont==500) {  //5 segundos 
	        // Acá entra cada 5 segundos (10 ms x 500)
	        cont=0;
	        }
	thread_sleep_for(10); // Espera en 10 ms para no bloquear  
        // este delay sería conveniente en el loop principar (no en la función)
        }

2024-07-27 08:17 UTC, Joanna20Carrion commented on main.cpp
> +        }
Gracias por la recomendación, lo tendré en cuenta para corregir esa parte del código.

2024-07-27 19:50 UTC, closed without merging